spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskmanager?useSSL=false&serverTimezone=UTC
    username: root
    password: sua_senha_aqui
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true